# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - mkdir -p build/{{.CLI_ARGS | dir}}
      - jinja2 {{.CLI_ARGS}} | pandoc -o  build/{{.CLI_ARGS | replace ".md.j2" ".html"}}
  all:
    cmds:
      - for x in $(find * -name '*.md.j2' ! -name 'szablon*'); do task -- $x; done