# https://taskfile.dev

version: "3"

tasks:
  build:
    internal: true
    cmds:
      - codebraid pandoc --no-cache --overwrite {{.name}}.md -o {{.name}}.html
      - sed 's/style="width:99%;"//g' -i {{.name}}.html
      - sed 's/class="dataframe"//g' -i {{.name}}.html
      - cat {{.name}}.html | xclip -selection clipboard
      - echo '<link rel="stylesheet" href="https://thermores.pwr.edu.pl/files/cache/projects/157/pl/css/style.css?1670941512">' | cat - {{.name}}.html | sponge {{.name}}.html
    silent: true

  podstawy-termodynamiki:
    cmds:
      - task: build
        vars:
          name: podstawy-termodynamiki
  teoria-maszyn-cieplnych:
    cmds:
      - task: build
        vars:
          name: teoria-maszyn-cieplnych
  przenoszenie-ciepla:
    cmds:
      - task: build
        vars:
          name: przenoszenie-ciepla
  wymiana-ciepla-i-wymienniki:
    cmds:
      - task: build
        vars:
          name: wymiana-ciepla-i-wymienniki
  termodynamika:
    cmds:
      - task: build
        vars:
          name: termodynamika
